### ISSUE TITLE
FileNotFoundError:\logs\\scan.log

### ISSUE THREAD

**Issue by garchaaman19** [flipkart-incubator/Astra#106]
When I try to run api.py I get the error

`C:\Users\INTEL\Downloads\Astra-master\API>python api.py
Traceback (most recent call last):
  File "api.py", line 38, in <module>
    from astra import *
  File "..\astra.py", line 8, in <module>
    import utils.logs as logs
  File "..\utils\logs.py", line 12, in <module>
    fh = logging.FileHandler(path)
  File "C:\Users\INTEL\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\INTEL\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\INTEL\\Downloads\\Astra-master\\API\\logs\\scan.log`

O.S- Windows 10,
Python -3.7

**Comment by abhisheksimion** [comment]
Please use python 2.7 it's the basic requirement.

**Comment by garchaaman19** [comment]
okay I will try.
