### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'SMTP'

### ISSUE THREAD

**Issue by abhisheksimion** [flipkart-incubator/Astra#109]
I get NoSectionError when I try to run "python api.py".

`C:\Tools\Astra\API>python api.py
Traceback (most recent call last):
  File "api.py", line 38, in <module>
    from astra import *
  File "../astra.py", line 34, in <module>
    from utils.email_cron import email_start_cron
  File "../utils\email_cron.py", line 20, in <module>
    emails = send_email()
  File "../utils\sendemail.py", line 11, in __init__
    self.host = get_value('config.property','SMTP','ip')
  File "../utils\config.py", line 21, in get_value
    return Config.get(section,name)
  File "C:\Tools\Python27\lib\ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'SMTP'`

Note: Using Python 2.7

**Comment by Sybrid203** [comment]
Error still persists.
