### ISSUE TITLE
getting weird template not found issues

### ISSUE THREAD

**Issue by msumit** [flipkart-incubator/Astra#20]
Trying with a test url on localhost, but getting a bunch of errors in logs

```
url http://localhost:3000/api/account.json
total_scan 1
scanid cfe2f0d1050bc56427e8644a593f7b7e
name dadasd
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sumitm/src/Astra/API/api.py", line 154, in view_dashboard
    return render_template('{}'.format(page))
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/Jinja2-2.8.1-py2.7.egg/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/Jinja2-2.8.1-py2.7.egg/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/Jinja2-2.8.1-py2.7.egg/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: favicon.ico

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 762, in inner
    srv.serve_forever()
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 597, in serve_forever
    HTTPServer.serve_forever(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 290, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 325, in handle_one_request
    return self.run_wsgi()
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 267, in run_wsgi
    execute(self.server.app)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 258, in execute
    write(data)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 233, in write
    self.send_header('Server', self.version_string())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
```

**Comment by sagarpo** [comment]
Favicon.ico file is missing on the server you can ignore that error.  IOError needs to be fixed.  Which flask version are you using? Was your mongoDB running when you started Astra?

**Comment by msumit** [comment]
@sagarpo yes, mongo was running.

**Comment by sagarpo** [comment]
@msumit Ok. Were you able to scan any URL? also let me know your flask version. I will look into it. Thanks
