### ISSUE TITLE
Unable to connect to the internal /option/[task-id] endpoint when running sqli

### ISSUE THREAD

**Issue by ajmaradiaga** [flipkart-incubator/Astra#47]
Details from logs: 
```
INFO:root:sqlmap is started
ERROR:root:Exception from sendrequest HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://127.0.0.1:8775/option/601d901a0bd4d0ed/set (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c547c1390>: Failed to establish a new connection: [Errno 111] Connection refused',)))
```

https://github.com/flipkart-incubator/Astra/blob/e4f60378ae2dc964db528789514c9844a2981af2/modules/sqli.py#L26-L34

Exception raised:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../astra.py", line 122, in modules_scan
    sqli_check(url,method,headers,body,scanid)
  File "../modules/sqli.py", line 119, in sqli_check
    set_option_status = set_options_list(url,method,headers,body,taskid)
  File "../modules/sqli.py", line 36, in set_options_list
    if options_list.status_code == 200:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by ajmaradiaga** [comment]
Thanks, it does work now.
