### ISSUE TITLE
AttributeError: "NoneType"

### ISSUE THREAD

**Issue by dderusha** [flipkart-incubator/Astra#53]
When I run a scan, I get the following error. 

`Process module-scan:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../astra.py", line 106, in modules_scan
    cors_main(url,method,headers,body,scanid)
  File "../modules/cors.py", line 72, in cors_main
    result = cors_check(origin,option_response.headers)
AttributeError: 'NoneType' object has no attribute 'headers'`

scanid=NONE 

When I run a scan, my results are always "In Progress"
TY

**Comment by sagarpo** [comment]
@dderusha Hey this seems an SSL issue(OpenSSL in Mac).  It was failing because of SSL handshake issue. It's working fine on my ubuntu box.  If you find a way to fix this on mac, let us know. I have tried updating openssl and python but no luck. 

Ref: https://stackoverflow.com/questions/36896631/osx-python-ssl-handshake-error
