### ISSUE TITLE
Recursive import failing: "ImportError: cannot import name main"

### ISSUE THREAD

**Issue by pwna5aurus** [flipkart-incubator/Astra#93]
The API/api.py is importing * from astra which recursively imports API/api.py, and the logic to skip the import on iterative imports:
```
if os.getcwd().split('/')[-1] != 'API':
    from API.api import main
```

 isn't working.  Here's the trace-back:

```
Traceback (most recent call last):
  File "astra.py", line 38, in <module>
    from API.api import main
  File "C:\Pentest\Astra\API\api.py", line 38, in <module>
    from astra import *
  File "C:\Pentest\Astra\astra.py", line 38, in <module>
    from API.api import main
ImportError: cannot import name main
```

**Comment by sagarpo** [comment]
@pwna5aurus: Will look into this. BDW I have noticed from your comment that you are using windows box to run astra. We have not tested it in windows so we are not sure if that will work. I would recommend to use it linux or mac. Also, ImportError mentioned in your comment is limited to CLI version so you can use web interface of Astra to run the scan.

**Comment by brianonn** [comment]
Same problem on OS X with python 2.7.15

**Comment by coffee-cat-007** [comment]
I have tried with couple of versions 2.7.14 & 2.7.15 still no luck.

**Comment by sagarpo** [comment]
@brianonn : Are you able to access through web interface?

**Comment by sagarpo** [comment]
@coffee-cat-007 : Try through web interface.

**Comment by CreativeWolf** [comment]
Heya,

> OS: Ubuntu 16.04
> Python version 2.7

Here's the traceback while trying to run the web interface

> Traceback (most recent call last):
>   File "api.py", line 38, in <module>
>     from astra import *
>   File "../astra.py", line 14, in <module>
>     from core.zapscan import *
> ImportError: No module named zapscan

While there is zapscan.py inside the directory core, looks like the path is not read

**Comment by kashaziz** [comment]
Commenting out line 38 in api.py works with web interface.
# from astra import *

**Comment by lisa50loves** [comment]
I have to try this

**Comment by true-hero** [comment]
astra.py has to be launched from directory /app/API, like this:
`/app/API # python /app/astra.py --help`

**Comment by NelsonGaleano** [comment]
A mi me funciono de la siguiente manera:
```
cd Astra/API/
python ../astra.py --help
```
y listo!
Gracias @true-hero por la idea!
